class UserOrderData {
  int idpesanan,
      idpenumpang,
      idrute,
      totalbayar,
      idpetugas,
      harga,
      idtransportasi;

  String kodepemesanan,
      tanggalpemesanan,
      tempatpemesanan,
      kodekursi,
      tujuan,
      tanggalberangkat,
      jamcekin,
      jamberangkat,
      createdat,
      updatedat,
      namapenumpang,
      kode,
      ruteawal,
      ruteakhir,
      keterangan,
      kodetp,
      name;

  UserOrderData({
    this.idpesanan,
    this.kodepemesanan,
    this.tanggalpemesanan,
    this.tempatpemesanan,
    this.idpenumpang,
    this.kodekursi,
    this.idrute,
    this.tujuan,
    this.tanggalberangkat,
    this.jamcekin,
    this.jamberangkat,
    this.totalbayar,
    this.idpetugas,
    this.createdat,
    this.updatedat,
    this.namapenumpang,
    this.keterangan,
    this.kodetp,
    this.kode,
    this.ruteawal,
    this.ruteakhir,
    this.harga,
    this.idtransportasi,
    this.name,
  });
}
